name: Smoke (app + DB + SerpAPI)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Start app (background)
        run: |
          nohup npm run start >/tmp/next.log 2>&1 &
          echo $! > /tmp/next.pid

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:3000/api/_diag/env

      - name: Show env diag
        run: curl -sS http://127.0.0.1:3000/api/_diag/env | jq .

      - name: DB diag
        run: curl -sS http://127.0.0.1:3000/api/_diag/db | jq .

      - name: Run smoke test
        run: npm run smoke
        env:
          BASE_URL: http://127.0.0.1:3000

      - name: Upload server log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: next-log
          path: /tmp/next.log

      - name: Stop app
        if: always()
        run: |
          if [ -f /tmp/next.pid ]; then kill $(cat /tmp/next.pid) || true; fi
